auth:
  username: devops
  password: 5ZDrROHoKAjIjxA
  database: devopsdb


image:
  repository: bitnamilegacy/postgresql
  tag: 17.6.0-debian-12-r4

primary:
  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi