grafana:
  admin:
    existingSecret: monitoring-grafana-sealed
    userKey: admin
    passwordKey: admin-password
  persistence:
    enabled: true
    storageClassName: local-path
    size: 10Gi


prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
