apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.namespace }}-{{ .Values.nameOverride }}-redirect-to-https
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true