replicaCount: 1
nameOverride: backend-dev
revisionHistoryLimit: 2
image:
  repository: fodpapnor99/backend-app
  tag: 7f113f2f
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
ingress:
  enabled: true
  className: traefik
  host: backend.dev.local
  path: /
probes:
  readiness:
    path: /health/ready
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /health/live
    initialDelaySeconds: 10
    periodSeconds: 20
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
namespace: applications-dev
