replicaCount: 1

nameOverride: frontend-dev

revisionHistoryLimit: 2

image:
  repository: fodpapnor99/frontend-app
  tag: 7fd92244
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  host: frontend.dev.local
  path: /

probes:
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 20

namespace: applications-dev
