apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: frontend-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/fodpapnor/Devops-GitOps.git
    path: applications/frontend-chart
    targetRevision: HEAD

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: applications-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true