apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAu0wWT7TKsyDdjyIukcC4lgLtE0LfPEEExJk/E7zgLLCPr3A9ZEy6lyGKgjkeL5ptqgFjMIeHTxS9Tl8tDJQZawdZf3KG51d4zkn0U2vKY2nWtH9DWSQF0PzQFeD7T92xZmiOVWCKasQslJrSclqMqq3uokObeIU7JBTJQTdU2Fx9vDZfyx5QkGTxmWNKwsK35iYypABFkPe+cEwRv4mPSJHXXzdz4UQXz/PrvE8Zawiu+fBh8r8QT4fNSQVVN9eYxxQGDoZrGOsjDCWnequnisDw2eg9kEyVN5+j4Wk2+0oWIvVD122hDYelVcMikI88XLv1O0uMcs4tejXcViY8lfs44qZIAixUJTMv+KW0V6Ygg1DojhLbWaairq2/bjzLdU/WPY5PFoOF6Ykjg1gkWhZmpUmgW3I5HAG5GpvDSi4gWywZktMJmwvUlKnsDFv+vFplVSEbbyaMFUuUnw4R98HVqe9Dv3I9VdkIv7nePm7x6O7YRQ72FIqKGM2ViTy/8Mym9Hn9Y7yBB5R/IzbuE4KhiAgbxtFAodEWSvPRqK3rpNeX1QwVEkRMDLU5/8CXcycG371d44CopJB8+vQcqKgO/wEMwgvZn2QBwdi6RjEX1wDjn3YQ8tEAoU1o7mTdNcCosRSDoRCT9c9RluizPqwL/rbaFAMMpaXvqq3XmEMAT2evAGlx3dPo44PMqyJLC/XgHJM4Vk69fhFUALKLh9VKyOQll3u4GWnVm3YVuYb+glpX/ocBD
    admin-user: AgBHj8fOxF58zi5d66/fsWDpuKusHOAkO3xzvx/jPYKlQUkm7YrTbgzl2SI9kYtfJQXYDCGUXp1Wmyr7tRchEJBQTDME/wOhnUKKER0ojnG6Z7IyyJ8EMVbA2utAX2G2gXtOvSxaSFibT1jpbeEHjqBl7vqDyT5j/yiKXKXZJcctnTrmcwfF2+pGT3WSCB3CYc7r9GcBlctl96IK+OAO+gTF24Vnfy8IMeNLqaMqwGY+SQXHDfuvzbS15t7/ht9YEVcILVP4eH5SeH16BrzL/q9Eof8+RrqtyDxk3QYYydoEU/JiFCY4yLcjti8DICNI07X/qKGKC/7g15P2u3t6dbiDgU6SUO6yGBAcbDB/xd096XrzOoj7eyGEd7eLNtuQlvfvZZUlavDApYgt00KWfi/2Zv1/PRRv6oQC6EIAeP44QWVYs0Edo/QgdBB7ZwyrF13k7XSD/8brEicyS6DUhOcjmmqxxnEWatRohO0L5ljaLSXEITk1eVHwiQOdiKMfJ+1erMZusoHNMnDBejErwI4f4PeSeUXiPJBOJxDcBDMoE5tjYBM+zy1fKKciEpJgtERTnBCCqRV+h4xo5LNwpJmU1rcuG4W7opDfwBEank16YM7XTQMVwnDEXKnKmXjENEqiTamYrXkzW0f5bz79vN1wcNE3fu0QTZnKcWm6dW7QZidTrYu6lxmlI3Byy2simkK10SuuOg==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana
      namespace: monitoring
    type: Opaque