apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC8VEKiHlWzvaIk0Gz56YhDu4Azybu+28JbjixB7lQTKl7jbinznKw05IOb8blzRJhab8kPzcK2NBFzW7kJ8c6ZphkU6ea4Npuky7DKMPMitucGIczNYltEqUE5yca6bYAQUIJhvCK/3NvGOZcdZD4HCCTMUxniShOt4FWls/qQ01qBGK9XDvt2pTTiVOK01Rh2qLtrCvLucVQKN5WA8hntb6+YWWInmQ56wmZ3KI5ChPcxI3GaXHNRQlRZkr67GUXBtaw8BXJTQ+7oJnBKdZoLTBcU8MYeg1DbjoXIBjc4YkMgJH1+1IYSQl3TEc0iWFqxgI8XLfShBTGYdm2orf8MPzM98n3Ca3ekOqbhm0rQVcMZy9zYiXWjarH8qpVJOHX2Z/i0GZhHzsQsokiQEdx7Q7/8pxBckuVVqRojG17iVeERi210DbEUJboQNAtEjZJbDNSLcslY2b3n4cRVd1rDSNbupcrGyld4su1UHXTuNDiKi8fJpZB8MsNGDGTpFDHLypzQt4MQO5C9FaGaruUDRjppbNQ80e0Dssac9PDMedv0e+aYMtKICRyDgslKKTtoJiSm9onOpPT/T6RQDUtkgVONBFEtXhSz3v+orT4BwXgCSc+ypQtJLIvrLxqukQvVU1u6Rqw++cwmnF4DyFdnMU6JP92Ak14qbiKXLI5zsgbVESzCikIfd5zRK24xMuEKRY0buibcSU/n5aR/8GL+cCb9+wFfpsf+kVFdGoi+vGtofo/jFhOu
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana
      namespace: monitoring