apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-postgresql
  namespace: database
spec:
  encryptedData:
    postgresql-password: AgAR8MZcMFTl2/is/ovShLEa8jUkcr0MLS9M/no0cxzst58Z/MrPcLdNJ0NRUej2eA9yUMH32VWWcp3iGOdnawGGeZaT9TVHnLi9nROZTxWinOmj8gxyR94msSUt+QjdYGCKP2mYJPG0lqJBWfgcTTuktVEV0xdxOw5xPxDjLi5+MCQC4nvMQBZK6yXZ0IxfaZ4jMFcGtnTYNGxzVBy+yRIj80AzAJXMTEAL9rA5KXPzJLRlE0nwrp0ESrhZqrADeDILDhHb19UutFQyQ9FVBekGy/NhHl+UdtGVYF49kNoUUeSZoLy8pmdW+c+AjozbiMMaBHOs4qphW/0U1NKb1xZkhfEhDgt4cRUTPX/Xlga03TOGWmjgwn/cW9CwiBZ9/Xy5jMbhnG8yT4oop0aFSYsEVL4NvlcrlWTe9R3vxQIIUUeNvJxb4gjHZczjR61PeAXC221mYzs2Sc2aDaWZpL3DYVRdg+GDqKRrX1Of3tQacIx416NnjTBFQ3RuZqLoPSfXczumBnRE//jqpl4OMGByuQ/n/8QMx7x8Pxd9WvEor/PD/PUAinmJd81CLb8TF8f2V/KKsveTI7bhT50+7Tfsq8873yIMKffbf0K3VUns5/93dS1tuJpSxRzkTo2vjfv3DSUpGbpGg/+d1r0nct5I/xtZQiwabT5owklj7JgAU+8+YA30szoaUlz5Sp0ICtqK9ooPW7tut8IhrurZ2MHgFIy6UA==
  template:
    metadata:
      name: postgres-postgresql
      namespace: database