apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-postgresql
  namespace: database
spec:
  encryptedData:
    postgres-password: AgC8LvpJKCxt6BvuMo566VQ4YGdsX08HHQj5I1Jzja0lIodAyRZrggBr9WTHb/R6pk7eqopn17QTCAeiz/hITF/DI6It579sJ207TJukK3WJnWRkyvKx2RLcr8Es1qUr/uu/T7quk6mXsmnLM6Gbh/4e55Yj1/HpnktDY8ASD3yM9gNsMt+QTmMO7wsIaOKaKHdch1idEdZBfK1jpBg6Ftd8YehoVhmsIM/OUx696rK3VAzX8ymNCvkOg62wVT5mPXlWOPYsWHnuCZ3ymTdZu5gsTSfjFsxjCcGTcjEvg0gkOoAbzCLxql97GQN5Yfrjp5TMuxayOz9/b8fKGse0NbyOHQ9q4g5KSqSGE/yHev78+6DozVqjrMb00/0PG6OMRL/VVI86ckzE5duOYQ02Jghk3V7zwakavteIIxSsW7gCdIUsko3Zc1cp4udHrPzsOov8EIjjkLV3fgl3TttbErJq/VdprNLJDV2KdngiNbYMgkO0IR9Rpqn91VXF2xtq3Icc47aKBWQOA4dSmGmuSQV1pHulhn8+aoP0aZjnPJE2/C17JzxlB+nL9ONQmoXgspQGSeoPM0SNZlKA5VNzhOqYlq+g7EaYHciy57yp4ryuLHP9z3Y2kLBYS7d9l/Wg0hLq1LdoWnrrkZXx/1gdOJk0ET8BVrJX0NYBXmAwWidw7QF002lIOmNRZc8p/xEB3X5WhCk8YmuEEL/Q
  template:
    metadata:
      name: postgres-postgresql
      namespace: database
    type: Opaque