apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-postgresql
  namespace: database
spec:
  encryptedData:
    postgres-password: AgCbfAkz1aHHF9DyXWwb1Tw43296jMBLD2gvE8JxzMayFdOAYVgfYXUqgLk/LG5/pqdngLZ7rENtbcx9PHKdD7YeYIpN1//Up/hohCSIr8n5060Lp399xWqAEeC6jJ/5/VFVRPdAAji7Snu/ul+MbxJukUcLJkNGqQDRrSrxYEo9HFpNTn2HMJZHzLeQLLv/760lh8tzhYNIYbfMaQo7z8ncwcbm5+jGEPU7NPybWP7XSRW8XjfKqQn9uYs3TCrDeYWoy4VMECA+HBabjAmtwn77BrkX1CPz6yLsVlJl8QqZ70VYk8oue2TVO6/QFDks5jdskmedY9wmihs9/0xri1PyQcJi8YM7Vt1mMJwlOZ71Cr7AeRQI0nYo3+3SJ6syViok4h2+zGvBSFe9G/HeRE9R4pCSXhSChAGMIfmHuyePzpRvz8VMMXscoynQsmP0jyXoJ3Of/Ddwu64CVUK+N5lR+SeRXhuuzweIZdvYDV/zn1isxYhwS7Ga9EwnKDM0/alfDuYsiLuzRBqZ9W98BkxqdLGHwsZppbMx0QtiR+ssJ97PDAVWNiErLDdkcAc77Vy68utVxyJfMI6gsRDF/aY3XgI+T2u2YtIpKuM+4m4m8R5awj5BKnibZcII62Gkgk9mU0KI0OaHeZdxJJN13CdhGwaEZuxJMJOnBrGCHIrm+I5mnCpVSxCn6FPqRjz6jnbDZcU+1ehvh8IlOalqgeCO8bFiCA==
  template:
    metadata:
      name: postgres-postgresql
      namespace: database