apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      releaseName: vault
      values: |
        server:
          ha:
            enabled: false

          standalone:
            enabled: true

          replicas: 1

          dataStorage:
            enabled: true
            size: 5Gi
            storageClass: "standard"

        ui:
          enabled: true

        injector:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    
    ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
        - /spec/template/spec/containers