apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      releaseName: vault
      values: |
        server:
          ha:
            enabled: true

            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true

                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_disable = 1
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}
          
          standalone:
            enabled: true

          dataStorage:
            enabled: true
            size: 5Gi
            storageClass: ""

        ui:
          enabled: true

        injector:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true